### ISSUE TITLE
Body parameters?

### ISSUE THREAD

**Issue by mwickens** [luckymarmot/Paw-SwaggerImporter#28]
Not sure what's supposed to be supported but I'm finding no body parameters get imported.

E.g., in this case:

``` yaml
  '/groupMailboxes/{groupMailboxID}/categories':
    parameters:
      - name: groupMailboxID
        in: path
        description: The ID of the group mailbox.
        required: true
        type: integer
    put:
      description: >-
        Update the categories associated with a group mailbox. Categories are
        added and removed as required.
      consumes:
        - application/json
      tags:
        - Group mailboxes
        - Categories
      produces:
        - application/json
      security:
        - basicAuth: []
      parameters:
        - name: body
          in: body
          description: What the categories list for the group mailbox should be.
          required: true
          schema:
            type: object
            properties:
              categories:
                type: array
                description: The category IDs.
                items:
                  type: integer
```
